// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
    "bytes"
    "encoding/json"
    "strings"

    "github.com/alecthomas/template"
    "github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/books": {
            "get": {
                "description": "Get all books",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "books"
                ],
                "summary": "Get all books",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseHTTP"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ResponseHTTP"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ResponseHTTP": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
    Version     string
    Host        string
    BasePath    string
    Schemes     []string
    Title       string
    Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
    Version:     "",
    Host:        "",
    BasePath:    "",
    Schemes:     []string{},
    Title:       "",
    Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
    sInfo := SwaggerInfo
    sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

    t, err := template.New("swagger_info").Funcs(template.FuncMap{
        "marshal": func(v interface{}) string {
            a, _ := json.Marshal(v)
            return string(a)
        },
    }).Parse(doc)
    if err != nil {
        return doc
    }

    var tpl bytes.Buffer
    if err := t.Execute(&tpl, sInfo); err != nil {
        return doc
    }

    return tpl.String()
}

func init() {
    swag.Register(swag.Name, &s{})
}
