// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assets" | "/assets/workspaces/[id]" | "/events" | "/inventory" | "/inventory/artifacts" | "/inventory/assets" | "/inventory/workspaces" | "/inventory/workspaces/[id]" | "/llm" | "/login" | "/registry" | "/scans" | "/scans/new" | "/schedules" | "/settings" | "/utilities" | "/vulnerabilities" | "/workflows" | "/workflows/[id]" | "/workflows/upload"
type AppRouteHandlerRoutes = "/api/mock/api/assets" | "/api/mock/api/login" | "/api/mock/api/new-scan" | "/api/mock/api/registry-info" | "/api/mock/api/registry-install" | "/api/mock/api/settings/yaml" | "/api/mock/api/stats" | "/api/mock/api/tasks" | "/api/mock/api/vulnerabilities" | "/api/mock/api/workflows" | "/api/mock/api/workspaces" | "/api/mock/health/ready"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/osm/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/mock/api/assets": {}
  "/api/mock/api/login": {}
  "/api/mock/api/new-scan": {}
  "/api/mock/api/registry-info": {}
  "/api/mock/api/registry-install": {}
  "/api/mock/api/settings/yaml": {}
  "/api/mock/api/stats": {}
  "/api/mock/api/tasks": {}
  "/api/mock/api/vulnerabilities": {}
  "/api/mock/api/workflows": {}
  "/api/mock/api/workspaces": {}
  "/api/mock/health/ready": {}
  "/assets": {}
  "/assets/workspaces/[id]": { "id": string; }
  "/events": {}
  "/inventory": {}
  "/inventory/artifacts": {}
  "/inventory/assets": {}
  "/inventory/workspaces": {}
  "/inventory/workspaces/[id]": { "id": string; }
  "/llm": {}
  "/login": {}
  "/osm/api/[[...path]]": { "path"?: string[]; }
  "/registry": {}
  "/scans": {}
  "/scans/new": {}
  "/schedules": {}
  "/settings": {}
  "/utilities": {}
  "/vulnerabilities": {}
  "/workflows": {}
  "/workflows/[id]": { "id": string; }
  "/workflows/upload": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
