// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/assets/workspaces/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets/workspaces/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/assets/workspaces/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/events">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/artifacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/artifacts">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/artifacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/assets">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/workspaces/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/workspaces/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/workspaces/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/workspaces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/workspaces">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/workspaces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/llm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/llm">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/llm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registry">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/scans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scans/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/scans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/scans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scans">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/scans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/schedules">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/utilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/utilities">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/utilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/vulnerabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vulnerabilities">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/vulnerabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/workflows/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/workflows/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/workflows/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflows/upload">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/workflows/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/assets">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/login">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/new-scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/new-scan">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/new-scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/registry-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/registry-info">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/registry-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/registry-install/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/registry-install">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/registry-install/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/settings/yaml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/settings/yaml">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/settings/yaml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/tasks">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/vulnerabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/vulnerabilities">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/vulnerabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/workflows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/workflows">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/workflows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/api/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/api/workspaces">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/api/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mock/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mock/health/ready">> = Specific
  const handler = {} as typeof import("../../../app/api/mock/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
