#!/usr/bin/env python3
import os
import sys
import time
import argparse
import urllib.parse
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

from core import utils


# portscan -i /tmp/target.txt -o '$WORKSPACE/portscan/$OUTPUT' -s '$WORKSPACE/portscan/summary.txt' -p '$PLUGINS_PATH'
def routine(args):
    target = args.input
    output = args.output

    os.system(f'cat {target} | unfurl -u format http://%d >> {output}-scheme.txt')
    os.system(f'cat {target} | unfurl -u format https://%d >> {output}-scheme.txt')
    os.system(f'cat {target} | unfurl -u format http://%d:%P >> {output}-port.txt')
    os.system(
        f'cat {target} | unfurl -u format https://%d:%P >> {output}-port.txt')
    os.system(f'cat {target} | unfurl -u format %d >> {output}-domains.txt')
    os.system(f'cat {target} | unfurl -u format %r >> {output}-root.txt')
    time.sleep(0.3)
    # os.system(f'cat {output}-domains.txt | {plugin}/massdns/bin/massdns -r {plugin}/massdns/lists/resolvers.txt -q -t A -o S -w {output}-rawmassdns.txt')


parser = argparse.ArgumentParser(description="VulnScan alias")
parser.add_argument('-i', '--input', action='store', dest='input', help='input')
parser.add_argument('-o', '--output', action='store', dest='output', help='output')

args = parser.parse_args()
routine(args)
